language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: nightly

install:
  - travis_retry composer install --no-interaction --prefer-source